### ISSUE TITLE
Could not build module 'TencentOpenApi'

### ISSUE THREAD

**Issue by gityoung** [ArchLL/HGTencentOpenAPI#1]
Could not build module 'TencentOpenApi'

**Comment by ArchLL** [comment]
这个问题我也无法解决，感觉是QQ自己的问题，先用上个版本吧

发自我的iPhone

**Comment by mr-huangjian** [comment]
可以参考下我的解决办法：https://juejin.cn/post/6916432417506983949/

**Comment by ArchLL** [comment]
非常感谢，我明天试试

发自我的iPhone

**Comment by ArchLL** [comment]
方法很有效👍
